version: '3.8'

services:
  db:
    image: bitnami/postgresql:latest
    container_name: db_cadastros
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=db_cadastros
    volumes:
      - db_cadastros_pg_data:/bitnami/postgresql

  backend:
    build:
      context: ./backend/cadastros  
    container_name: spring_boot_backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_cadastros:5432/db_cadastros
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    volumes:
      - ./backend/cadastros:/app
    working_dir: /app
    command: ["java", "-jar", "target/cadastros-0.0.1-SNAPSHOT.jar"]

  frontend:
    build:
      context: ./frontend/cadastros  
    container_name: angular_frontend
    ports:
      - '4200:4200'
    volumes:
      - ./frontend/cadastros:/app
      - node_modules:/app/node_modules  
    working_dir: /app
    command: ["sh", "-c", "npm install && npm start"] 
    depends_on:
      - backend

volumes:
  db_cadastros_pg_data:
  node_modules:  
